"""add_concept_contents_table

Revision ID: 4807d4a0a18a
Revises: 4a5b6c7d8e9f
Create Date: 2026-01-29 19:47:11.412645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4807d4a0a18a'
down_revision: Union[str, None] = '4a5b6c7d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_contents_task_id'), 'concept_contents', ['task_id'], unique=False)
    op.create_index(op.f('ix_concept_contents_user_id'), 'concept_contents', ['user_id'], unique=False)
    op.alter_column('chapters', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exercise_items', 'difficulty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('knowledge_nodes_code_key'), 'knowledge_nodes', type_='unique')
    op.drop_index(op.f('ix_knowledge_nodes_code'), table_name='knowledge_nodes')
    op.create_index(op.f('ix_knowledge_nodes_code'), 'knowledge_nodes', ['code'], unique=True)
    op.alter_column('subjects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('subjects_key_key'), 'subjects', type_='unique')
    op.alter_column('user_node_masteries', 'mastery',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'practice_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'correct_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_subject_profiles', 'onboarding_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subject_profiles', 'onboarding_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'not_started'::character varying"),
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'correct_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'practice_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'locked'::character varying"),
               existing_nullable=False)
    op.alter_column('user_node_masteries', 'mastery',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('subjects_key_key'), 'subjects', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('subjects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_nodes_code'), table_name='knowledge_nodes')
    op.create_index(op.f('ix_knowledge_nodes_code'), 'knowledge_nodes', ['code'], unique=False)
    op.create_unique_constraint(op.f('knowledge_nodes_code_key'), 'knowledge_nodes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('knowledge_nodes', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('exercise_items', 'difficulty',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('chapters', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_concept_contents_user_id'), table_name='concept_contents')
    op.drop_index(op.f('ix_concept_contents_task_id'), table_name='concept_contents')
    op.drop_table('concept_contents')
    # ### end Alembic commands ###
